name: Build Lint Test (BLT)
on:
  pull_request:
    branches-ignore:
      - pacman*
    paths-ignore:
      - "example/**"
      - "Dockerfile"
      - "**/builder-image.yml"

jobs:
  build:
    name: Build and test go-alpm
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jguer/yay-builder:latest
    env:
      GOFLAGS: -buildvcs=false
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Lint
        run: /app/bin/golangci-lint run ./...
      - name: Vulnerability check
        run: go install golang.org/x/vuln/cmd/govulncheck@latest && $(go env GOPATH)/bin/govulncheck ./...
      - name: Run Build and Tests
        run: make test
